CREATE TABLE ASSINANTE(
    ASS_ID INT PRIMARY KEY AUTO_INCREMENT,
    ASS_NOME VARCHAR(50),
    ASS_MAIL VARCHAR(30),
    ASS_CELULAR VARCHAR(11),
    CRIADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE ASSINATURA (
    TURA_ID INT PRIMARY KEY AUTO_INCREMENT,
    TURA_ATIVA TINYINT(1),
    ASSINANTE INT, 
    CONSTRAINT FK_ASS FOREIGN KEY (ASSINANTE) REFERENCES ASSINANTE(ASS_ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
    CRIADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE ENDERECO (
    END_ID INT PRIMARY KEY AUTO_INCREMENT,
    END_LOG VARCHAR(100),
    END_NUM INT(6),
    END_COMPL VARCHAR(20),
    END_BAIRRO VARCHAR(30),
    END_CIDADE VARCHAR(100),
    END_UF VARCHAR(2),
    END_CEP VARCHAR(8),
    MORADOR INT,
    CONSTRAINT FK_END FOREIGN KEY (MORADOR) REFERENCES ASSINANTE(ASS_ID)
   	ON UPDATE CASCADE
    ON DELETE SET NULL,
    CRIADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO ASSINANTE (ASS_NOME,ASS_MAIL,ASS_CELULAR) VALUES ("Carlos","carlos@email.com","12345678910");
INSERT INTO ASSINANTE (ASS_NOME,ASS_MAIL,ASS_CELULAR) VALUES ("Julia","Julia@email.com","12345678911");
INSERT INTO ASSINANTE (ASS_NOME,ASS_MAIL,ASS_CELULAR) VALUES ("Maria","Maria@email.com","12345678912");
INSERT INTO ASSINANTE (ASS_NOME,ASS_MAIL,ASS_CELULAR) VALUES ("Ricardo","Ricardo@email.com","12345678913");
INSERT INTO ASSINANTE (ASS_NOME,ASS_MAIL,ASS_CELULAR) VALUES ("João","João@email.com","12345678914");

INSERT INTO ASSINATURA (TURA_ATIVA,ASSINANTE) VALUES (1,4);
INSERT INTO ASSINATURA (TURA_ATIVA,ASSINANTE) VALUES (0,3);
INSERT INTO ASSINATURA (TURA_ATIVA,ASSINANTE) VALUES (1,2);
INSERT INTO ASSINATURA (TURA_ATIVA,ASSINANTE) VALUES (1,1);
INSERT INTO ASSINATURA (TURA_ATIVA,ASSINANTE) VALUES (0,5);

INSERT INTO ENDERECO (END_LOG, END_NUM, END_COMPL, END_BAIRRO, END_CIDADE, END_UF, END_CEP, MORADOR) VALUES ("ENDERECO 01",123,"CASA 01","BAIRRO 01","SÃO PAULO","SP","01234567",1);
INSERT INTO ENDERECO (END_LOG, END_NUM, END_COMPL, END_BAIRRO, END_CIDADE, END_UF, END_CEP, MORADOR) VALUES ("ENDERECO 02",123,"CASA 11","BAIRRO 02","SÃO PAULO","SP","11234567",2);
INSERT INTO ENDERECO (END_LOG, END_NUM, END_COMPL, END_BAIRRO, END_CIDADE, END_UF, END_CEP, MORADOR) VALUES ("ENDERECO 03",123,"CASA 21","BAIRRO 03","SÃO PAULO","SP","21234567",3);
INSERT INTO ENDERECO (END_LOG, END_NUM, END_COMPL, END_BAIRRO, END_CIDADE, END_UF, END_CEP, MORADOR) VALUES ("ENDERECO 04",123,"CASA 31","BAIRRO 04","SÃO PAULO","SP","31234567",4);
INSERT INTO ENDERECO (END_LOG, END_NUM, END_COMPL, END_BAIRRO, END_CIDADE, END_UF, END_CEP, MORADOR) VALUES ("ENDERECO 05",123,"CASA 41","BAIRRO 05","SÃO PAULO","SP","41234567",5);
INSERT INTO ENDERECO (END_LOG, END_NUM, END_COMPL, END_BAIRRO, END_CIDADE, END_UF, END_CEP, MORADOR) VALUES ("ENDERECO 06",123,"CASA 51","BAIRRO 06","SÃO PAULO","SP","51234567",6);
